sudo: required

services:
- docker

language: php
php:
  - '5.6'

env:
  global:
  - secure: "mUMiJf3dqY6mgstrkGLVcg9MhSIBtzJTSG1z6Ot1VYSW9qdVjzOKN9rtAEmtkxmlM/DgBlz1Sfe9x/f5Yiw8B+ULnmz8Y4IZnm4tlTyN0CjbzyZ66F5/38YeEvR276ea64LNoUVkW48CrDq+6eiOvrReSEtci6tKinWDeKTUlHodQ9V5ehaJek2MuM5flV18jnVg1sTO7ai/OIUSqzdQFwfahrgNhP39hUkm7nB7yamAJb06LC+GUIVQPNNdZ/6grUEC2jnuWNYSpT4JRQM31Ps0LPEO6mNFFnluZFpyTrhbaEIDGmQasO3N1Z3x1qZarV5XKcgb0dAS0wGXUDjITLDI2I/mHBFDEazyW7zzWnkIc0bm7h2aOmGYj6CQPO3gPS1AN6tAkw6NbXwgj2FCDgGR4ahrGw/aIIKAKuCY0f8ickL2A2mwmAD2RywzmLTbtT5PtU+UnKo5k6i+ATdHQjnd/7/KNA5wbK2DgIfhGfiaErOCgu3DglTkWyoQQ5CArW7UX+3pybws2ANChWxc1BM9SlnSRKHsKIuTkZamWyjQ2+d1ju2H2h0rM58P3jSJOQcGxesxCMUEn93eHrHHBdT2SiENywT0HgUjxNHWle2GdkeCVDd2CsJRWEJVH+4PrNYoYh71D6TNa8pwNtqpz0bV1uGNQY6nB8FA96YGfco=" #DOCKER_USER
  - secure: "clmFRxkssVEyUEIUCLOExXuFF0763VGPflQAWyZ+LkXpKra6tJc1Hh/poEUbkw05Fvd/uIwPbNeeemg8HOjdIW+udYq4U4ycu1VNiSIgJKNX4hmoVl5HnmQMz6nZHLQ/4dbCSIp8hGQeOBgxvngiCrR5EvKEW68thu7380sXG8zwtLl9b71YTAUQLOkvVVH4bPRtN6N5KK81VMI/5PNF3Qsud84QPAYrXgu5h+zZ8nt7gD2K8JE25z1NNxdJWBB4rqUBXbWJsTbKBJZHzdRr5pqjTYdZt7NqBZYFxIyI8ZW5xfJZn0Xi6vRasJnpxw1vOA1SX7RKcGZies5+cqn8OwHW5AttGmWHKgIAoJl6T832FrIegtHc/jpzb1sIO+o84bt5DGYsUCLWsM4AIFQkq+QFtPs/DoySRGlNlnuxKHe/XSFozOKnqBRRu/SRzG9rXlRb/yjvNGPQ33/q5FHha2rSOQnZekC4/sgZWMcnpNBLXtByhTrl/nh+ZonQG+M6FX4ZNh824K2RG8VqfQ9YAdM16VWd/FyMQ23g4IbrxfslKJmGPDltZwxyMdmS7//691ER1Zo1Bp2ak3Cig8G82HkHjroaxZc6ZNWP/R3c4sbJY9gBiWdngxRlXsmF3w+UeHbXp4r1/iRSYXRxL3nSX1N+HPPWb+P8kO6SqHUkp8Q=" #DOCKER_PASS

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

script:
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      export DOCKER_IMAGE_VERSION=$TRAVIS_TAG;
      export RADPHP_VERSION=$TRAVIS_TAG;
    else
      export RADPHP_VERSION="dev-$TRAVIS_BRANCH";
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        export DOCKER_IMAGE_VERSION="latest";
      else
        export DOCKER_IMAGE_VERSION="$TRAVIS_BRANCH";
      fi
    fi
  - docker build --build-arg=RADPHP_VERSION=$RADPHP_VERSION --target=radphp-app -t radphp/app:$DOCKER_IMAGE_VERSION .

after_script:
  - docker push radphp/app
